Dockerfile, deployment-files/nginx.conf, docker-compose.yml
updated configurations to use inferno paths instead of crucible_smart_app
Removed unicorn from dev image
=> Update to Inferno

lib/sequence_base.rb, lib/sequences/01_conformance_sequence.rb, lib/sequences/02_dynamic_registration_sequence.rb, lib/sequences/03_patient_standalone_launch_sequence.rb, lib/sequences/04_provider_ehr_launch_sequence.rb, lib/sequences/05_openid_connect_sequence.rb, lib/sequences/06_token_introspection_sequence.rb, lib/sequences/07_token_refresh_sequence.rb, lib/sequences/08_argonaut_query_sequence.rb, lib/sequences/09_argonaut_profiles_sequence.rb, lib/sequences/10_additional_resources_sequence.rb, lib/tasks/tasks.rake, models/test_result.rb, test/unit/sequence_validation_test.rb, views/test_list.erb, views/test_result_details.erb
Adds support for test id and extended reference information which are reflected in the database, UI and csv exports.
Reference Issue: #3
=> Add Test ID and Extended Reference Information

README.md, views/layout.erb
=> Update Readme to reflect inferno branding

lib/sequence_base.rb, lib/tasks/tasks.rake, models/test_result.rb, test/unit/sequence_validation_test.rb
Just a simple renaming based on recent feedback with updates to variables for consistency.
=> change Extended Reference to Reference and ext_ref to ref

public/css/styles.css, public/js/app.js, views/sequence.erb, views/test_list.erb
=> X-Browser Bugfixes

lib/app/endpoint/home.rb, public/js/app.js
Does support launching other tests as well as rerunning tests (so you could send someone a direct link to the test execution you're doing and it would run just as it did on your machine when you clicked the button)
=> Autorun conformance for newly created FHIR Servers

lib/app/utils/assertions.rb, test/unit/assertions_test.rb, test/unit/tls_tester_test.rb
Fixed TLS tests and added/updated some tests.
Looks better:
Tests passing:
=> TLS test fix

config.ru, config.yml, lib/app.rb, lib/app/endpoint.rb, lib/app/endpoint/landing.rb, lib/app/models.rb, lib/app/utils/logging.rb
First cut at being able to better log (and configure logging across the application).
You can now:
- Turn on and off logging
- Choose to log to file or STDOUT
- Pick logging level
=> add logging configuration

Gemfile, Gemfile.lock, config.yml, lib/app/models/testing_instance.rb, lib/app/sequence_base.rb, lib/app/sequences/02_dynamic_registration_sequence.rb, lib/app/sequences/02a_manual_registration_sequence.rb, lib/app/sequences/03_patient_standalone_launch_sequence.rb, lib/app/sequences/04_provider_ehr_launch_sequence.rb, lib/app/utils/exceptions.rb, lib/app/utils/web_driver.rb, lib/app/views/details.erb, lib/tasks/tasks.rake, script_example.json
Still needs some work around error handling and cleaning up, I'm sure.  But standalone launch now works.
I'd like to get this into development because there are a handful of changes to the models that I would like to get in.
=> Headless cli with standalone working

README.md, docker-compose.yml
This fixes an issue in the docker-compose and also provides a link to some troubleshooting documentation.
=> Update Docker and add some troubleshooting for windows

.rubocop.yml, Gemfile, Gemfile.lock, lib/app/endpoint/home.rb
- Style changes to make rubocop happier and code more readable
- Added some minor code documentation
- https://github.com/siteadmin/inferno/commit/5f355c597bf49e186d722a08094559a5474a7f4d can run multiple sequences and handle missing sequences (i.e. if you use `Run All`, and one of the sequences cannot be matched it is skipped)
=> House Cleaning Home.rb

lib/app/models/supported_resource.rb, lib/app/views/state_status.erb, test/model/supported_resource_test.rb, test/sequence/dynamic_registration_test.rb
Minor Updates to the client state view:
- Remove "Conformance Statement Resource Support" before supported resources have been identified
- Add client secret when the instance is used as a confidential client
- Removed some unnecessary commas
=> Update client state view

lib/app/endpoint/home.rb, lib/app/views/details.erb, lib/app/views/sequence.erb, public/css/styles.css
- f91151a Fixes a bug which made the screen get progressively darker
- b52fef9 makes some formatting changes to `home.rb`
- ddac8d9 changes uses of `demodulize` to `sequence_name`
=> Smoothing Over Extensibility Changes

Gemfile.lock, README.md, lib/app/module.rb, lib/app/modules/argonaut/argonaut_patient_sequence.rb, lib/app/utils/assertions.rb, lib/tasks/tasks.rake, script_example.json, test/rake/tasks_test.rb
=> WIP: Update Rake and CLI

lib/app/modules/smart/smart_discovery_sequence.rb
This is only testing that the required items are supplied and not blank
=> Add test for well-known endpoint

lib/app/endpoint/home.rb, lib/app/models/testing_instance.rb, lib/app/views/guided.erb, lib/app/views/report.erb, public/css/styles.css, public/js/app.js
=> Adding report view

lib/app/endpoint/home.rb, lib/app/endpoint/landing.rb
Only test cases that failed will be expanded
=> Expand only failed test cases

lib/app/modules/argonaut/argonaut_procedure_sequence.rb, lib/app/modules/smart/openid_connect_sequence.rb, lib/app/modules/smart/standalone_launch_sequence.rb, lib/app/modules/uscdi/document_reference_sequence.rb, lib/app/sequence_base.rb, public/css/styles.css
- Ensure procedure references are properly saved.
- Scroll bar for long request urls:
- Some other things
=> Minor Updates

.gitignore, README.md, Rakefile, lib/app/modules/argonaut/argonaut_patient_read_only_sequence.rb, test/integration/instance_page_test.rb, test/sequence/openid_connect_test.rb
FYI @radamson -- I'm pretty sure that me upping the expected # of failures for the OpenID Connect tests is correct, but could you just double check for me?
=> Self test fixes

lib/app/endpoint/home.rb, lib/app/models/request_response.rb, lib/app/models/sequence_result.rb, lib/app/sequence_base.rb, lib/app/views/report.erb, lib/app/views/state_status.erb, lib/app/views/test_case.erb, public/css/styles.css
Changed report UI. 
Show optional results in test cases. 
Find request count and last sequence time via database.
Fix redirect URI in client state
=> Report fixes

lib/app/module.rb, lib/app/modules/onc_module.yml, lib/app/views/guided.erb, lib/app/views/test_case.erb, public/js/app.js
Added button to rerun skipped tests for each group. 
I'm not sure if I should fix the launch/patient scope issue (during second launch attempt) in this PR. Let me know if I should.
=> Rerun skipped

lib/app/modules/argonaut/argonaut_allergy_intolerance_sequence.rb, lib/app/modules/argonaut/argonaut_careplan_sequence.rb, lib/app/modules/argonaut/argonaut_careteam_sequence.rb, lib/app/modules/argonaut/argonaut_condition_sequence.rb, lib/app/modules/argonaut/argonaut_device_sequence.rb, lib/app/modules/argonaut/argonaut_diagnostic_report_sequence.rb, lib/app/modules/argonaut/argonaut_goal_sequence.rb, lib/app/modules/argonaut/argonaut_immunization_sequence.rb, lib/app/modules/argonaut/argonaut_medication_sequence.rb, lib/app/modules/argonaut/argonaut_medication_statement_sequence.rb, lib/app/modules/argonaut/argonaut_observation_sequence.rb, lib/app/modules/argonaut/argonaut_procedure_sequence.rb, lib/app/modules/argonaut/argonaut_smoking_status_sequence.rb, lib/app/modules/argonaut/argonaut_vital_signs_observation_sequence.rb, lib/app/modules/core/capability_statement_sequence.rb, lib/app/modules/onc_module.yml, lib/app/modules/smart/dynamic_registration_sequence.rb, lib/app/modules/smart/ehr_launch_sequence.rb, lib/app/modules/smart/manual_registration_sequence.rb, lib/app/modules/smart/openid_connect_sequence.rb, lib/app/modules/smart/smart_discovery_sequence.rb, lib/app/modules/smart/standalone_launch_sequence.rb, lib/app/modules/smart/token_introspection_sequence.rb, lib/app/modules/smart/token_refresh_sequence.rb, lib/app/modules/uscdi_module.yml, lib/app/views/default.erb, public/css/styles.css
Adds overview text to sequences and details to each group.  The group details are now also displayed in the developer view.
=> Adding details on sequences and sequence groups.

lib/app/modules/smart/dynamic_registration_sequence.rb, lib/app/modules/smart/manual_registration_sequence.rb, lib/app/sequence_base.rb, lib/app/views/default.erb, lib/app/views/guided.erb, lib/app/views/test_case.erb, public/js/app.js
I'm leaving it specific to URIs right now, but it should be easy to expand this to be generic in the future if needed.
=> show uris during registration sequences

lib/app/modules/smart/openid_connect_sequence.rb
Use fhirUser insteand of profile claim
=> check fhirUser instead of profile

lib/app/views/default.erb, lib/app/views/guided.erb, lib/version.rb, public/js/app.js
This is a hotfix to our v1.0 release.  It is addressed separately in the upcoming 2.0 release.
=> Fixes issue where client secrets not being saved

lib/app/models/sequence_result.rb, lib/app/sequence_base.rb, lib/app/views/report.erb, lib/app/views/test_case.erb, lib/app/views/test_inputs.erb, public/css/styles.css
Displays inputs in both the report and as a tab in the test case.
=> Report test inputs

lib/app/views/guided.erb, lib/app/views/report.erb, public/css/styles.css
Fixes the issue where the progress bar on the guided view wraps when there are pass/fail indicators on all the steps.
=> Fix progress bar wrapping.

lib/app/views/state_status.erb
=> Fix duplicated title in state status.

lib/app/modules/onc_program_module.yml
=> Update program mode text

lib/app/modules/onc_program_module.yml
Minor wording update
**Before:**
**After:**
=> Minor update to Program Module Landing Page

lib/app/models/sequence_result.rb, lib/app/modules/smart/manual_registration_sequence.rb, lib/app/sequence_base.rb, lib/app/views/report.erb, lib/app/views/test_case.erb, lib/app/views/test_outputs.erb, public/css/styles.css, public/js/app.js
Display state changes after running sequences.
=> Show state changes

lib/app/modules/argonaut/argonaut_conformance_sequence.rb, lib/app/modules/us_core_r4/us_core_r4_capability_statement_sequence.rb
Address Github issues 186 and 187. Changed "Capability" to "Conformance" and added some links.
=> Conformance statement GitHub issues

lib/app/modules/argonaut/argonaut_careteam_sequence.rb, lib/app/utils/validation.rb, test/fixtures/care_team.json, test/sequence/argonaut/argonaut_careplan_sequence_test.rb, test/sequence/argonaut/argonaut_careteam_sequence_test.rb
Issue described in https://github.com/siteadmin/inferno/pull/197
=> Fix careteam skip issue

config.yml, lib/app/views/index.erb, public/js/app.js
Added link to select a preset. Go to https://inferno.healthit.gov/inferno/#preset-[preset_id] to preselect a preset using the preset_id from the config file. 
ex. http://localhost:4567/#preset-site_healthit_gov
=> added link to select presets

lib/app/models/sequence_result.rb, lib/app/models/test_result.rb, lib/app/sequence_base.rb, lib/app/utils/result_statuses.rb, test/model/sequence_result_test.rb, test/model/test_result_test.rb, test/shared/result_status_tests.rb
Refactored sequence_base.rb with @Jammjammjamm
=> Refactoring

lib/app/endpoint/home.rb, lib/app/helpers/browser_logic.rb, lib/app/views/default.erb, lib/app/views/guided.erb, public/css/styles.css, public/js/app.js
Added a progress bar for when tests are running.
=> Progress bar

lib/app/modules/onc_program/document_reference_sequence.rb, lib/app/modules/onc_program/provenance_sequence.rb, lib/app/utils/validation.rb, test/fixtures/document_reference.json, test/fixtures/r4_provenance.json, test/sequence/onc_program/onc_program_document_reference_test.rb, test/sequence/onc_program/onc_program_provenance_test.rb, test/sequence/r4_provenance_sequence_test.rb
Fixes a nil reference error on the dstu2 tests for careplan/careteam.  Also added a few tests for dstu2 provenance and documentreference.
=> Fix dstu2 test issues

public/css/styles.css
Updated border color on Next/Back/Run buttons to match their background color.
=> Update button border color

config.yml
I turned off TLS checking by default in the config by mistake, this reverts that.
Also slightly alters the name of the test presets.
=> Turn on TLS checking and tweak preset name.

lib/app/modules/onc_program_module.yml, lib/app/modules/onc_program_r4_module.yml, lib/app/views/guided.erb
Slight name change to the program tests so that the title of the `Report` tab makes more sense.
=> Remove Tests at end of some modules and update report title.

README.md, lib/app/utils/web_driver.rb, lib/tasks/tasks.rake, script_example.json
* Updates README to fix examples and other minor changes
* Fixes minor incorrect updates made to command line interface
* Improves webdriver code so less waiting is required
=> Task fixes

.gitignore, Gemfile.lock, lib/app/endpoint/home.rb, lib/app/models/testing_instance.rb, lib/app/modules/argonaut/argonaut_conformance_sequence.rb, lib/app/modules/core/capability_statement_sequence.rb, lib/app/modules/smart/smart_discovery_sequence.rb, lib/app/modules/smart/standalone_launch_sequence.rb, lib/app/modules/us_core_module.yml, lib/app/modules/us_core_r4/clinicalnotes_sequence.rb, lib/app/modules/us_core_r4/us_core_r4_capability_statement_sequence.rb, lib/app/utils/assertions.rb, lib/app/views/guided.erb, lib/version.rb, test/fixtures/us_core_r4_clinicalnotes_diagrpt_bundle.json, test/fixtures/us_core_r4_clinicalnotes_docref_bundle.json, test/model/testing_instance_test.rb, test/sequence/us_core_r4/clinicalnotes_sequence_test.rb
Created sequence for ClincalNotes, two text fixtures and text text files for the sequence
=> FI-271 clinical notes

lib/app/endpoint/oauth2_endpoints.rb
=> FI-273: Fix url

generators/uscore-r4/generator.rb, lib/app/modules/us_core_r4/pediatric_bmi_for_age_sequence.rb, lib/app/modules/us_core_r4/pediatric_weight_for_height_sequence.rb, lib/app/modules/us_core_r4/us_core_allergyintolerance_sequence.rb, lib/app/modules/us_core_r4/us_core_careplan_sequence.rb, lib/app/modules/us_core_r4/us_core_careteam_sequence.rb, lib/app/modules/us_core_r4/us_core_condition_sequence.rb, lib/app/modules/us_core_r4/us_core_device_sequence.rb, lib/app/modules/us_core_r4/us_core_diagnosticreport_lab_sequence.rb, lib/app/modules/us_core_r4/us_core_diagnosticreport_note_sequence.rb, lib/app/modules/us_core_r4/us_core_documentreference_sequence.rb, lib/app/modules/us_core_r4/us_core_encounter_sequence.rb, lib/app/modules/us_core_r4/us_core_goal_sequence.rb, lib/app/modules/us_core_r4/us_core_immunization_sequence.rb, lib/app/modules/us_core_r4/us_core_location_sequence.rb, lib/app/modules/us_core_r4/us_core_medicationrequest_sequence.rb, lib/app/modules/us_core_r4/us_core_medicationstatement_sequence.rb, lib/app/modules/us_core_r4/us_core_observation_lab_sequence.rb, lib/app/modules/us_core_r4/us_core_organization_sequence.rb, lib/app/modules/us_core_r4/us_core_patient_sequence.rb, lib/app/modules/us_core_r4/us_core_practitioner_sequence.rb, lib/app/modules/us_core_r4/us_core_practitionerrole_sequence.rb, lib/app/modules/us_core_r4/us_core_procedure_sequence.rb, lib/app/modules/us_core_r4/us_core_smokingstatus_sequence.rb
FI-264
Save the resource before validating. 
To test, run the medicationrequest sequence and make sure test MedicationRequest-08 doesn't skip.
=> save resources before validating

lib/app/models/server_capabilities.rb, lib/app/modules/argonaut/argonaut_conformance_sequence.rb, lib/app/modules/core/capability_statement_sequence.rb, lib/app/modules/us_core_r4/us_core_r4_capability_statement_sequence.rb, lib/app/utils/assertions.rb, test/model/server_capabilities_test.rb
This PR fixes an assertion that couldn't fail and DRYs up the conformance tests a little.
=> FI-302: Fix broken SMART assertion

generators/uscore-r4/generator.rb, generators/uscore-r4/templates/sequence.rb.erb, lib/app/modules/us_core_r4/pediatric_bmi_for_age_sequence.rb, lib/app/modules/us_core_r4/pediatric_weight_for_height_sequence.rb, lib/app/modules/us_core_r4/us_core_allergyintolerance_sequence.rb, lib/app/modules/us_core_r4/us_core_careplan_sequence.rb, lib/app/modules/us_core_r4/us_core_condition_sequence.rb, lib/app/modules/us_core_r4/us_core_device_sequence.rb, lib/app/modules/us_core_r4/us_core_diagnosticreport_lab_sequence.rb, lib/app/modules/us_core_r4/us_core_diagnosticreport_note_sequence.rb, lib/app/modules/us_core_r4/us_core_documentreference_sequence.rb, lib/app/modules/us_core_r4/us_core_encounter_sequence.rb, lib/app/modules/us_core_r4/us_core_goal_sequence.rb, lib/app/modules/us_core_r4/us_core_immunization_sequence.rb, lib/app/modules/us_core_r4/us_core_location_sequence.rb, lib/app/modules/us_core_r4/us_core_medicationrequest_sequence.rb, lib/app/modules/us_core_r4/us_core_medicationstatement_sequence.rb, lib/app/modules/us_core_r4/us_core_observation_lab_sequence.rb, lib/app/modules/us_core_r4/us_core_patient_sequence.rb, lib/app/modules/us_core_r4/us_core_practitioner_sequence.rb, lib/app/modules/us_core_r4/us_core_practitionerrole_sequence.rb, lib/app/modules/us_core_r4/us_core_procedure_sequence.rb, lib/app/modules/us_core_r4/us_core_smokingstatus_sequence.rb
Searches that are marked as "SHOULD" will be optional.
=> FI-320 make SHOULD searches optional

lib/app/modules/onc_program/onc_smart_discovery_sequence.rb
=> updated link to well known capabilities test

lib/app/views/default.erb, lib/app/views/guided.erb, lib/app/views/index.erb, lib/app/views/report.erb, lib/app/views/state_status.erb, lib/app/views/test_details.erb, lib/app/views/test_result_details.erb, public/css/styles.css, public/js/app.js
Ran through [WAVE](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) and fixed all of the critical errors, most of the warnings, and most of the contrast issues.  I didn't fix all of the warnings and all of the contrast issues because they were more intrusive fixes and I'm unsure of their real value.
To test, I suggest walking through the program edition tests and ensuring that none of my style tweaks did anything too obtrusive from your perspective.
Requests do …
=> Fi-46 accessibility fixes

lib/version.rb
=> Update version to  2.7.0

lib/app/modules/uscore_v3.0.0/us_core_medicationrequest_sequence.rb, lib/app/modules/uscore_v3.0.0/us_core_medicationstatement_sequence.rb, lib/app/modules/uscore_v3.0.0/us_core_practitionerrole_sequence.rb
This fixes autogenerated code that wasn't committed in FI-430, so it has no substantive changes.
**Submitter:**
Name:
Name:
=> FI-466 merge fix

Gemfile.lock
=> FI-495 Bump json-jwt gem due to moderate security issue.

lib/modules/bdt_module.yml
=> Rename BDT module.

generator/uscore/templates/sequence.rb.erb, generator/uscore/uscore_generator.rb, lib/modules/uscore_v3.1.0/pediatric_bmi_for_age_sequence.rb, lib/modules/uscore_v3.1.0/pediatric_weight_for_height_sequence.rb, lib/modules/uscore_v3.1.0/us_core_allergyintolerance_sequence.rb, lib/modules/uscore_v3.1.0/us_core_careplan_sequence.rb, lib/modules/uscore_v3.1.0/us_core_careteam_sequence.rb, lib/modules/uscore_v3.1.0/us_core_condition_sequence.rb, lib/modules/uscore_v3.1.0/us_core_diagnosticreport_lab_sequence.rb, lib/modules/uscore_v3.1.0/us_core_diagnosticreport_note_sequence.rb, lib/modules/uscore_v3.1.0/us_core_documentreference_sequence.rb, lib/modules/uscore_v3.1.0/us_core_encounter_sequence.rb, lib/modules/uscore_v3.1.0/us_core_goal_sequence.rb, lib/modules/uscore_v3.1.0/us_core_immunization_sequence.rb, lib/modules/uscore_v3.1.0/us_core_implantable_device_sequence.rb, lib/modules/uscore_v3.1.0/us_core_location_sequence.rb, lib/modules/uscore_v3.1.0/us_core_medication_sequence.rb, lib/modules/uscore_v3.1.0/us_core_medicationrequest_sequence.rb, lib/modules/uscore_v3.1.0/us_core_observation_lab_sequence.rb, lib/modules/uscore_v3.1.0/us_core_organization_sequence.rb, lib/modules/uscore_v3.1.0/us_core_patient_sequence.rb, lib/modules/uscore_v3.1.0/us_core_practitioner_sequence.rb, lib/modules/uscore_v3.1.0/us_core_practitionerrole_sequence.rb, lib/modules/uscore_v3.1.0/us_core_procedure_sequence.rb, lib/modules/uscore_v3.1.0/us_core_provenance_sequence.rb, lib/modules/uscore_v3.1.0/us_core_pulse_oximetry_sequence.rb, lib/modules/uscore_v3.1.0/us_core_smokingstatus_sequence.rb
This PR will add some descriptions to the tests
**Submitter:**
Name:
Name:
=> FI-375 - Update test descriptions

generator/uscore/uscore_generator.rb, lib/modules/uscore_v3.1.0/pediatric_bmi_for_age_sequence.rb, lib/modules/uscore_v3.1.0/pediatric_weight_for_height_sequence.rb, lib/modules/uscore_v3.1.0/us_core_allergyintolerance_sequence.rb, lib/modules/uscore_v3.1.0/us_core_careplan_sequence.rb, lib/modules/uscore_v3.1.0/us_core_careteam_sequence.rb, lib/modules/uscore_v3.1.0/us_core_condition_sequence.rb, lib/modules/uscore_v3.1.0/us_core_diagnosticreport_lab_sequence.rb, lib/modules/uscore_v3.1.0/us_core_diagnosticreport_note_sequence.rb, lib/modules/uscore_v3.1.0/us_core_documentreference_sequence.rb, lib/modules/uscore_v3.1.0/us_core_encounter_sequence.rb, lib/modules/uscore_v3.1.0/us_core_goal_sequence.rb, lib/modules/uscore_v3.1.0/us_core_immunization_sequence.rb, lib/modules/uscore_v3.1.0/us_core_implantable_device_sequence.rb, lib/modules/uscore_v3.1.0/us_core_location_sequence.rb, lib/modules/uscore_v3.1.0/us_core_medication_sequence.rb, lib/modules/uscore_v3.1.0/us_core_medicationrequest_sequence.rb, lib/modules/uscore_v3.1.0/us_core_observation_lab_sequence.rb, lib/modules/uscore_v3.1.0/us_core_organization_sequence.rb, lib/modules/uscore_v3.1.0/us_core_patient_sequence.rb, lib/modules/uscore_v3.1.0/us_core_practitioner_sequence.rb, lib/modules/uscore_v3.1.0/us_core_practitionerrole_sequence.rb, lib/modules/uscore_v3.1.0/us_core_procedure_sequence.rb, lib/modules/uscore_v3.1.0/us_core_provenance_sequence.rb, lib/modules/uscore_v3.1.0/us_core_pulse_oximetry_sequence.rb, lib/modules/uscore_v3.1.0/us_core_smokingstatus_sequence.rb
This PR makes the vread and history interaction tests optional. 
**Submitter:**
Name:
Name:
=> FI-518 - set optional interactions

lib/app/models/testing_instance.rb, lib/modules/core/capability_statement_sequence.rb, lib/modules/smart/ehr_launch_sequence.rb, lib/modules/smart/manual_registration_sequence.rb, lib/modules/smart/shared_launch_tests.rb, lib/modules/smart/smart_discovery_sequence.rb, lib/modules/smart/test/shared_launch_tests_test.rb, lib/modules/smart/test/token_refresh_sequence_test.rb, lib/modules/smart/token_refresh_sequence.rb, lib/modules/us_core_guidance/us_core_r4_capability_statement_sequence.rb
Various copy edits and consistency updates.
=> Update sequence wording

config.yml
=> FI-543 Remove bulk data from community config.

lib/app/ext/fhir_client.rb, lib/app/models/request_response.rb, lib/app/models/test_result.rb, lib/app/sequence_base.rb, lib/app/utils/logged_rest_client.rb
This branch adds a timestamp to recorder request/responses so that they are displayed in the correct order.
Before:
```
INFO | Inferno | GETTING: https://api.logicahealth.org/MacVR4/data/Condition/SMART-Condition-14
INFO | Inferno | GETTING: https://api.logicahealth.org/MacVR4/data/Condition/SMART-Condition-16
INFO | Inferno | GETTING: https://api.logicahealth.org/MacVR4/data/Condition/SMART-Condition-17
INFO | Inferno | GETTING: https://api.logicahealth.org/MacVR4/data/Condition/SMART-Condition-20
INFO | Inferno | GETTING: https://api.logicahealth.org/MacVR4/data/Condition/SMART-Condition-22
INFO | Inferno | GETTING: https://api.logicahealth.org/MacVR4/data/Condition/SMART-Condition-21
INFO | Inferno | GETTING: https://api.logicahealth.org/MacVR4/data/Condition/SMART-Condition-19
INFO | …
```
=> FI-475: Fix request order

lib/modules/smart/shared_launch_tests.rb
This branch saves the parsed token response body in an instance variable so that it is accessible to other tests in the sequence.
=> Save token response body

Gemfile.lock
Bump rack to address a security vulnerability in 2.0.7.
**Submitter:**
- n/a Tests are included and test edge cases
Name:
Name:
=> FI-576: Bump rack to 2.0.8

config.yml, docker-compose.yml
**Submitter:**
- na Tests are included and test edge cases
Name:
Name:
=> Add validator service to docker-compose.

README.md
**Submitter:**
All N/A, just fixing a broken link.
Name:
Name:
=> issue #444 - fix broken link

config.yml, lib/app/endpoint.rb, lib/app/endpoint/home.rb, lib/app/helpers/configuration.rb, lib/app/utils/config_manager.rb, lib/app/views/layout.erb, test/fixtures/test_config.yml, test/unit/config_manager_test.rb
This branch updates the documentation in `config.yml` and removes some configuration settings which weren't actually being used.
=> FI-975: Update config.yml documentation

generator/bdt/bdt-structure.json, generator/bdt/templates/bdt_base.rb, generator/bdt/templates/sequence.rb.erb, lib/modules/bdt/authorization_sequence.rb, lib/modules/bdt/bdt_base.rb, lib/modules/bdt/download_endpoint_sequence.rb, lib/modules/bdt/group_level_export_sequence.rb, lib/modules/bdt/metadata_sequence.rb, lib/modules/bdt/patient_level_export_sequence.rb, lib/modules/bdt/status_endpoint_sequence.rb, lib/modules/bdt/system_level_export_sequence.rb, lib/modules/bdt_module.yml
Update BDT service to the latest Aug. 11th commit
=> FI-942 BDT update

resources/smart_scheduling_links/StructureDefinition-vaccine-location.json
Updates the Vaccine Location profile for SMART Scheduling Links to:
* require an address
* stop calling a URL an "email"
* Set VTrckS identifier count to allow `0..*`, and warn if one doesn't exist
=> Update vaccine location profile

lib/modules/smart_scheduling_links/smart_scheduling_links_basic_sequence.rb
This removes redundant tests now that we have more robust built-in FHIR validation, and cleans up a few things as well.
=> Clean up scheduling tests.

lib/modules/ips/ips_operation_document_sequence.rb, lib/modules/ips/ips_operation_summary_sequence.rb
Fix failed unit tests caused by missing test links
=> Fixed failed unit tests 

lib/modules/us_core_guidance/clinicalnotes_sequence.rb, lib/modules/us_core_guidance/test/clinicalnotes_sequence_test.rb
Fix the issue reported at #551 
Migrated Clinical Notes sequences from Inferno Program to Inferno Community
Test using steps mentioned in #551
=> Migrate ClinicalNotes Sequence from Program edition

.codeclimate.yml, lib/modules/smart_scheduling_links/smart_scheduling_links_basic_sequence.rb, lib/modules/smart_scheduling_links/test/fixtures/manifest_file.json, lib/modules/smart_scheduling_links/test/smart_scheduling_basic_test.rb
Added initial batch of test cases for scheduling.  Some tests are commented out at the moment.
=> Smart scheduling test cases

config.yml, generator/uscore/uscore_generator.rb, lib/modules/uscore_v3.1.1/us_core_organization_sequence.rb, lib/modules/uscore_v3.1.1/us_core_patient_sequence.rb, test/unit/sequence_base_test.rb
This PR is a community version of this closed pr: https://github.com/onc-healthit/inferno-program/pull/311/files
The location and sequence doesn't change because we're ignoring location, medication, and practitionerrole sequences in community.
=> change search by string
