app.rb

EventMachine has the ability to periodically send data out over an open connection.  By sending out data every 20 seconds, browsers won't close the connection preemptively.
To test, you can try the SSL problem we have internally, and note that every 20 seconds content will print out to the javascript console.  The browser's 'loading' spinner (in chrome it is in the tab) should continue to spin.  After about 3 minutes the page will refresh (because the SSL socket connection finally timed out).
Before, the browser would timeout after 30 seconds.  In chrome, the 'loading' spinner will stop and the page would be 'dead', with the test run modal never doing anything.
There is more we can do here, but I think this addresses the core problem and I'd like to get it merged in quickly to make sure …

Prevent streaming from timing out.

---

app.rb

We allow users to cancel sequences in progress.  In practice this is currently only used in the EHR launch sequence, which is why we missed it the first time around.
To recreate the error, try starting an EHR launch, but then click 'cancel'.  That will cause a test result without a test_id to be saved, which causes the webpage to break.
This just makes sure that test_id gets passed to the test result properly.

Test Results created from a cancellation don't save test_id.

---

app.rb

Fixes two bugs introduced from a refactor in #13.
* A string that printed out javascript did not properly interpolate variables into string
* A variable was incorrect causing the server to crash
This should have been picked up by walking through the application manually.  Since we are going to be adding in selenium-like functionality, I may add browser-interaction-level tests so we can catch issues like this.

Fix bug from js code refactor.

---

README.md
views/details.erb
views/layout.erb

This resolves some minor issues:
* Adds an alert targeted solely at Internet Explorer warning about Inferno support
* Adds language to the README about supported browsers
* Adds an alert to the Save button about how tests may not be stored perpetually

Add browser support warning, README information, and save state warning

---

Gemfile.lock
lib/app/sequences/01_conformance_sequence.rb
lib/app/sequences/03_patient_standalone_launch_sequence.rb

This is a very frequent issue -- the server provides OAuth endpoints but isn't explicit about SMART support.  We updated the client so that we can be relaxed about this issue (note the 3.0.6 client bump).
Perhaps we should add a warning about this?  Notably, the SMART r2 reference server has this issue.

Fix issue when server states OAuth endpoints but is not explicit about smart support.

---

lib/app/views/details.erb

OIDC and Token Refresh weren't showing all the required params in the popup before the run. OIDC should show the id_token and Token Refresh should show the refresh token.

Add missing params for OIDC and Token Refresh sequences.

---

lib/app/endpoint/home.rb

When you run the standalone launch sequence, for example, after finishing the results weren't auto opening.

Fix issue where launches dont auto open results.

---

lib/app/sequences/03_patient_standalone_launch_sequence.rb
lib/app/sequences/04_provider_ehr_launch_sequence.rb
lib/app/sequences/07_token_refresh_sequence.rb

If a server correctly passes back information like the id_token and the refresh_token, they should be saved, even if something else goes wrong within the same test (like a header is missing).  This is largely a test granularity problem, and in this case too many things were logically put into a single test (and something early fails, preventing other working things from running).  I think it could be broken out even more, but this is a start.
To replicate, use the following FHIR server:
```
https://launch.smarthealthit.org/v/r2/sim/eyJrIjoiMSIsImoiOiIxIiwiYiI6InNtYXJ0LTEwOTg2NjcifQ/fhir
```
Any `client_id` can be used, and password on the login prompt can be used.
When you run the standalone launch sequence, the id_token isn't saved because an earlier assertion (regarding headers) fails. …

Break out launch header checks into separate tests to be more dev friendly.

---

lib/app/sequences/06_token_introspection_sequence.rb
lib/app/sequences/07_token_refresh_sequence.rb
lib/app/sequences/08h_argonaut_observation_sequence.rb
test/unit/sequence_validation_test.rb

Since IDs are 'hardcoded' in a sense, it is easy for them to fall out of sequential order.  We do need them to be hardcoded though to establish traceability across versions from a requirements perspective.  So to help mitigate the problem, this adds a test to make sure that tests ids are sequential and there are no 'holes'.
This test exposed 3 times when this problem occurred, so this PR fixes those instances.
Note: I do not give a solution for when a 'hole' may legitimately exist yet.  We can push that off until it becomes an issue.

Sequential ids

---

lib/app/sequences/01_conformance_sequence.rb

Technically `application/json` is an allowed content type in the conformance statement.

Allow application/json content type.

---

lib/app/sequences/03_patient_standalone_launch_sequence.rb
lib/app/sequences/04_provider_ehr_launch_sequence.rb
lib/app/sequences/07_token_refresh_sequence.rb

Token refresh was failing for confidential clients because it wasn't using the necessary authorization header, this adds that header.

Token Refresh for Confidential Clients

---

config.yml
lib/app/sequence_base.rb
lib/app/sequences/02_dynamic_registration_sequence.rb
lib/app/sequences/08a_argonaut_patient_sequence.rb
lib/app/sequences/08b_argonaut_allergy_intolerance_sequence.rb
lib/app/sequences/08c_argonaut_careplan_sequence.rb
lib/app/sequences/08d_argonaut_careteam_sequence.rb
lib/app/sequences/08e_argonaut_condition_sequence.rb
lib/app/sequences/08f_argonaut_device_sequence.rb
lib/app/sequences/08g_argonaut_diagnostic_report_sequence.rb
lib/app/sequences/08h_argonaut_observation_sequence.rb
lib/app/sequences/08i_argonaut_goal_sequence.rb
lib/app/sequences/08j_argonaut_immunization_sequence.rb
lib/app/sequences/08k_argonaut_medication_sequence.rb
lib/app/sequences/08l_argonaut_medication_order_sequence.rb
lib/app/sequences/08m_argonaut_medication_statement_sequence.rb
lib/app/sequences/08n_argonaut_procedure_sequence.rb
lib/app/sequences/08o_smoking_status_sequence.rb
lib/app/sequences/08p_vital_signs_observation_sequence.rb
lib/app/views/sequence.erb
public/css/styles.css

Adds a warning to users if the Conformance doesn't support the required resource for a sequence. 
Doesn't currently check for operations on those resources.

Conformance Supports Check

---

lib/app/models/resource_reference.rb
lib/app/models/testing_instance.rb
lib/app/sequence_base.rb
lib/app/sequences/08l_argonaut_medication_order_sequence.rb
test/fixtures/Medication_Reference.json
test/fixtures/medication_13.json
test/fixtures/medication_14.json
test/fixtures/medication_15.json
test/sequence/medication_order_sequence_test.rb
test/sequence/token_refresh_sequence_test.rb

- Provides testing for the medication order sequence making sure that all tests pass and that no duplicates are present
- Adds some details to the medication order sequence
- Tests all medication orders, not just the first
- Follows medicationReferences, if available

Medication Order Test and Fix for Duplicate Orders

---

config.yml
lib/app/sequences/01_conformance_sequence.rb
lib/app/sequences/02_dynamic_registration_sequence.rb
lib/app/sequences/03_patient_standalone_launch_sequence.rb
lib/app/sequences/04_provider_ehr_launch_sequence.rb
lib/app/sequences/06_token_introspection_sequence.rb

This resets TLS tests to not being optional.
Note that these were set to being optional in the first place because of a peculiarity when running this on MITRE's network.  When you disable the tls tests through the config, now a 'skip' will get rolled up to the sequence level.  We may consider adding a flag like 'disabled by configuration', which would be more generic and could be useful in the future. 
This also fixes the config and how it was accidentally set to disable tls tests by default during this sprint in an earlier PR.

TLS not optional

---

lib/app/modules/smart/dynamic_registration_sequence.rb
lib/app/views/default.erb
lib/app/views/guided.erb
public/js/app.js

save client secret during registration by moving it out of the confidential_client prerequisite field.

separate client confidential and client secret prerequisites

---

deployment-files/nginx.conf

Removing the X-Frame-Options header so that inferno can be placed in an iframe.

Remove frame option header

---

lib/app/endpoint/home.rb

This now redirects to the test set of the last run sequence or the default test set. 
Since I couldn't recreate this normally, I just went straight to this url which was able to reproduce the issue.
http://localhost:8080/inferno/oauth2/static/redirect?error=invalid_scope&error_description=Invalid%20scope;%20requested:%5BfhirUser,%20offline_access,%20openid,%20patient/*.read%5D&state={YOUR CLIENT STATE HERE}&scope=launch/patient%20patient/*.read%20openid%20offline_access%20profile%20launch%20user/*.*%20patient/*.*

handle redirect when no sequence is being run

---

lib/app/modules/argonaut/argonaut_allergy_intolerance_sequence.rb
lib/app/modules/argonaut/argonaut_careplan_sequence.rb
lib/app/modules/argonaut/argonaut_careteam_sequence.rb
lib/app/modules/argonaut/argonaut_condition_sequence.rb
lib/app/modules/argonaut/argonaut_device_sequence.rb
lib/app/modules/argonaut/argonaut_diagnostic_report_sequence.rb
lib/app/modules/argonaut/argonaut_goal_sequence.rb
lib/app/modules/argonaut/argonaut_immunization_sequence.rb
lib/app/modules/argonaut/argonaut_medication_order_sequence.rb
lib/app/modules/argonaut/argonaut_medication_sequence.rb
lib/app/modules/argonaut/argonaut_medication_statement_sequence.rb
lib/app/modules/argonaut/argonaut_observation_sequence.rb
lib/app/modules/argonaut/argonaut_patient_search_sequence.rb
lib/app/modules/argonaut/argonaut_procedure_sequence.rb
lib/app/modules/argonaut/argonaut_smoking_status_sequence.rb
lib/app/modules/argonaut/argonaut_vital_signs_observation_sequence.rb
lib/app/modules/bluebutton_demo/bluebutton_explanationofbenefit_sequence.rb
lib/app/modules/onc_program/document_reference_sequence.rb
lib/app/modules/onc_program/provenance_sequence.rb
lib/app/sequence_base.rb

I'm adding a validate_resource_item function in each sequence that does a validate_search_reply. This makes it so each sequence has a way to validate search results based on its own structure. 
I still need to implement the date check, but I'm not sure how to check if a date time falls within a period. It should be easy to add later though. Not sure if this is time-sensitive so just creating a pull request now.
Things I'm not sure about: 
It looks like clinicalStatus in the condition resource should be a code, but in HSPC it's just a string.
Argonaut says category is a valid search parameter for careplan, but FHIR DSTU2 says it isn't.

Extend search validation

---

lib/app/views/index.erb

Makes entering a FHIR server URL mandatory:
Before:
After:

make fhir_server url required

---

lib/app/endpoint/home.rb
lib/app/views/guided.erb
lib/app/views/report.erb
public/css/styles.css

It would be useful to see in the report which operational system performed the tests, and be able to get back to the live instance.  This adds the URI to the report.
It also fixes a bug where on the report section, the report stated 'Step 4 of 4' incorrectly.

Add inferno instance uri to report.

---

lib/app/endpoint/home.rb

To reproduce, run the standalone launch sequence in the ONC module. The failed tests should be open and not just the first sequence.

open failed sequences correctly

---

lib/app/views/default.erb
lib/app/views/guided.erb
lib/app/views/module_options.erb
public/css/styles.css

Displayed FHIR version in the heading:
And on the index page: 
But not for SMART:

display fhir version

---

lib/app/modules/onc_program_module.yml
lib/app/modules/onc_program_r4_module.yml
lib/app/modules/smart/smart_discovery_sequence.rb
lib/app/modules/smart_module.yml
lib/app/sequence_base.rb
lib/app/views/default.erb
lib/app/views/guided.erb
lib/app/views/module_options.erb
lib/app/views/state_status.erb

The fhir_version field in the yml files for configuring modules is now optional. If this field is filled, then the FHIR version is displayed on the index page, header, and in the state popup box. For example, the SMART module does not have a fhir_version. Also, the FHIR version was removed from the module titles. 
Index page: 
Header: 
State popup box:

Made fhir version optional

---

lib/app/views/default.erb
lib/app/views/guided.erb

Added more explanation and instruction to the EHR pop up for the EHR Launch tests.

added more instruction to EHR launch tests

---

.rubocop_todo.yml
lib/app/modules/argonaut/argonaut_careteam_sequence.rb
lib/app/modules/smart/ehr_launch_sequence.rb
lib/app/modules/smart/standalone_launch_sequence.rb
lib/app/modules/smart/token_refresh_sequence.rb
lib/app/utils/assertions.rb

Added checking for valid JSON to smart sequences token refresh, EHR launch, and standalone launch sequence.

Check for valid JSON

---

lib/app/views/guided.erb
public/css/styles.css
public/js/app.js

Added a "Continue" and "Back" button to the guided tests. The buttons appear after the test is run, no matter the result. The buttons have the same functionality as clicking the tabs at the top.

Add Continue button for guided tests 

---

config.yml
lib/app/endpoint.rb
lib/app/endpoint/home.rb
lib/app/endpoint/landing.rb
lib/app/views/index.erb
public/js/app.js

Adding a "domain" field to the presets in the config file will cause that preset to only appear if the base url of the current url is the same as the domain in the config file. If there is no domain specified in the config file, then the preset will always appear. This allows the presets to be configured for both localhost and for inferno.healthit.gov. 
These are the two base urls: 
https://inferno.healthit.gov/inferno/ (this one should be double checked)
http://localhost:4567

Try Me Base URL

---

lib/app/endpoint/home.rb
lib/app/models/testing_instance.rb
lib/app/utils/result_statuses.rb
lib/version.rb
public/css/styles.css

The rollup report didn't work properly because it required all sequences stored in inferno to have been passed.  Since we added the concept of modules and test_sets, this doesn't work anymore.  Updated to use the new test structures.
Also, before it would mark as 'fail', even if you hadn't run any tests yet.  Updated to mark as 'incomplete' if you hadn't passed everything but haven't failed anything either.

Fix report rollup

---

lib/app/models/testing_instance.rb
lib/version.rb
test/model/testing_instance_test.rb

See #235 
Somehow DataMapper isn't saving the patient_id when input by the user.  To replicate, run US Core R4 tests, run the Allergy Intolerance Sequence, enter any Bearer Token and Patient ID, and not that the patient_id is never persisted to the db and therefore isn't picked up by our tests.
Creating a hotfix and new patch version because this is a critical bug. We can merge back into development afterwards.

Patient ID not saving when input from a user (eg. US Core R4).

---

lib/app/endpoint/home.rb
lib/app/models/resource_reference.rb
lib/app/models/sequence_result.rb
lib/app/models/testing_instance.rb
lib/app/modules/argonaut/argonaut_careplan_sequence.rb
lib/app/modules/argonaut/argonaut_careteam_sequence.rb
lib/app/modules/argonaut/argonaut_observation_sequence.rb
lib/app/modules/argonaut/argonaut_smoking_status_sequence.rb
lib/app/modules/argonaut/argonaut_vital_signs_observation_sequence.rb
lib/app/sequence_base.rb
lib/app/utils/validation.rb
test/sequence/argonaut/argonaut_careteam_sequence_test.rb
test/unit/argonaut_fixture_test.rb

This branch modifies how resources are validated against a profile. Previously, passing a profile to `SequenceBase#test_resources_against_profile` didn't guarantee that the resources were actually validated against the specified profile. Now, when it receives a specific profile, it:
- Validates any resources which were saved and categorized as conforming to that profile
- If no resources have been saved with that profile, it checks `meta.profile` for resources which claim to conform to the profile and validates those
- If no resources were found, the test is skipped
I did a fair amount of refactoring while investigating this problem, so the actual bug fix is all in [this commit.](https://github.com/siteadmin/inferno/pull/224/commits/3fb4ba8383d8b8e2c77133512ca5a0433b46898a)
**NOTE:** the …

Fix DSTU2 CareTeam profile validation

---

lib/app/endpoint/home.rb
lib/app/views/guided.erb

In guided mode, updated the background while tests are running to the currently running test, instead of always defaulting to Discovery & Registration.

FI-265 update background

---

lib/app/modules/smart/smart_discovery_sequence.rb
lib/app/modules/smart/standalone_launch_sequence.rb
lib/app/utils/assertions.rb

Fixed issue where on redirect, if the returned oauth authorization uri is empty it will redirect to itself (also handle cases of invalid oauth authorization uri in general)
Added new assert_valid_http_uri 
Updated standalone_launch_sequence 
02 to assert that the oauth authorization endpoint is valid before attempting to redirect 
updated the other propagating tests to not crash when 02 fails to return a valid params and a valid tokens
Updated smart_discovery_sequence.rb
replaced uri checkes with the new assert_valid_http_uri

Fi 258 fail on launches if no auth

---

lib/app/modules/smart/token_refresh_sequence.rb
test/sequence/token_refresh_sequence_test.rb

Addresses #246 which was a request for improved testing on our token refresh.  We also made a number of changes, including:
* Condensed what used to be three tests into a single test, because we needed to duplicate that single test to handle multiple cases.  It was far too repetitive to keep the same test structure.
* Identified a number of minor issues in the SMART spec that went unnoticed earlier.  We had to change some of our tests to accommodate that (noted in the referenced issue).
* Significantly bulked up our self testing
You can try out these changes by executing out the refresh token sequence on any server

Test optional scope parameter in token refresh sequence

---

lib/app/models/testing_instance.rb

FI-266
Added R4 resources so that they are saved from reading the conformance statement. 
To test this, run the MedicationRequest sequence in HSPC. It should now run the read, vread, and history tests.

Save R4 resources from the conformance statement

---

generators/uscore-r4/generator.rb
generators/uscore-r4/metadata_extractor.rb
lib/app/modules/us_core_r4/pediatric_bmi_for_age_sequence.rb
lib/app/modules/us_core_r4/pediatric_weight_for_height_sequence.rb
lib/app/modules/us_core_r4/us_core_allergyintolerance_sequence.rb
lib/app/modules/us_core_r4/us_core_careplan_sequence.rb
lib/app/modules/us_core_r4/us_core_careteam_sequence.rb
lib/app/modules/us_core_r4/us_core_condition_sequence.rb
lib/app/modules/us_core_r4/us_core_device_sequence.rb
lib/app/modules/us_core_r4/us_core_diagnosticreport_lab_sequence.rb
lib/app/modules/us_core_r4/us_core_diagnosticreport_note_sequence.rb
lib/app/modules/us_core_r4/us_core_documentreference_sequence.rb
lib/app/modules/us_core_r4/us_core_encounter_sequence.rb
lib/app/modules/us_core_r4/us_core_goal_sequence.rb
lib/app/modules/us_core_r4/us_core_immunization_sequence.rb
lib/app/modules/us_core_r4/us_core_location_sequence.rb
lib/app/modules/us_core_r4/us_core_medication_sequence.rb
lib/app/modules/us_core_r4/us_core_medicationrequest_sequence.rb
lib/app/modules/us_core_r4/us_core_medicationstatement_sequence.rb
lib/app/modules/us_core_r4/us_core_observation_lab_sequence.rb
lib/app/modules/us_core_r4/us_core_organization_sequence.rb
lib/app/modules/us_core_r4/us_core_patient_sequence.rb
lib/app/modules/us_core_r4/us_core_practitioner_sequence.rb
lib/app/modules/us_core_r4/us_core_practitionerrole_sequence.rb
lib/app/modules/us_core_r4/us_core_procedure_sequence.rb
lib/app/modules/us_core_r4/us_core_smokingstatus_sequence.rb

FI-288
This PR sets the search parameters of the authorization tests to be the same as the first search's parameters. If there are no searches, then we won't do the authorization test.

Make authorization search params the same as first search

---

lib/app/views/test_list.erb

Removed tooltip because it was conflicting for another one (as in issue 289)

FI-289 removed tooltip on warning icon indicating redirect

---

lib/app/endpoint/oauth2_endpoints.rb
lib/app/endpoint/test_set_endpoints.rb
lib/app/ext/fhir_client.rb
lib/app/models/sequence_result.rb
lib/app/utils/oauth2_error_messages.rb
lib/tasks/tasks.rake
test/integration/oauth2_endpoints_test.rb

This branch adds happy path tests and separates `launch` and `redirect` into separate endpoints. When these endpoints successfully find a testing instance, they `pass` to a shared route which continues test execution.

FI-273: Refactor OAuth2 endpoints 

---

lib/app/modules/argonaut/argonaut_conformance_sequence.rb
lib/app/modules/onc_program/onc_standalone_launch_sequence.rb
lib/app/sequence_base.rb
lib/app/views/test_case.erb

`TestResult`s used to display in a non-obvious/nondeterministic order (see the "before" screenshot below) after a test was cancelled. This is because of how test indexes are assigned to base tests in extended sequences. See ticket https://oncprojectracking.healthit.gov/support/browse/FI-291 for more information.
No longer reassign test indexes for the base tests when they're added to extended sequences, e.g. the `CapabilityStatementSequence` tests in the `ArgonautConformanceStatement` sequence. See the "after" screenshots below for examples of the Cancelled EHR Launch Sequence test results, a completed test suite, and a test suite that hasn't yet been run, to show that they are all sorted as expected.
Cancelled test suite:
Completed test suite:
Not-run test suite:

FI-291: Fix Sort Order of Extended Sequences

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/default_pr_template.md

This PR adds 3 templates to the repository, through the use of the `.github/` hidden folder:
* `ISSUE_TEMPLATE/bug_report.md`: A template for external users to report suspected bugs through the Inferno "Issues" tab. Selectable by the user if they want to report a bug.
* `ISSUE_TEMPLATE/feature_request.md`: A template for external users to request features in Inferno through the "Issues" tab. Selectable by the user if they want to request a feature.
* `PULL_REQUEST_TEMPLATE/default_pr_template.md`: A Pull Request Checklist, to be filled out by the submitters and both reviewers on every Inferno PR.

FI-98: Add issue and PR templates to the repo

---

lib/app/views/report.erb

This was already partially taken care of in #272
There used to be a space when added when pluralizing test on when the number of ommited were greater than one.  This fixes the report view case.

FI-321 Fix pluralization on omit reporting.

---

README.md

This PR attempts to fix a broken image link when the README is displayed in docker hub.
**Submitter:**
- N/A Tests are included and test edge cases
- N/A Tests/code quality metrics have been run locally and pass
Name: @okeefm 
Name:

FI-350: Fix broken image in docker hub

---

lib/app/views/test_list.erb

Tests with warnings currently display two tooltips which can be viewed by slowly moving the cursor over the warning icon:
This branch removes the erroneous tooltip.
**Submitter:**
- N/A Tests are included and test edge cases
Name:
- N/A The tests appropriately test the new code, including edge cases
Name:
- N/A The tests appropriately test the new code, including edge cases

FI-356: Remove double warning tooltip

---

lib/app/views/request_details.erb

Currently, the request details view does not show the request URL. This branch will add the url and request direction to the request details view. You can view this by pressing the "details" link next to one of the requests in the HTTP Requests tab.
**Submitter:**
Name: Rob Scanlon
Name:

FI-268 add request url to request details

---

lib/app/endpoint/test_set_endpoints.rb

This PR fixes the "cancel sequence" button so it doesn't cause a server error when clicked (see below for a screenshot of the "before" behavior).
**Submitter:**
Name:
Name:

FI-421 cancel sequence fix

---

lib/app/models/inferno_test.rb
lib/app/modules/smart/token_refresh_sequence.rb
lib/app/sequence_base.rb
lib/app/utils/exceptions.rb
test/sequence/smart/token_refresh_sequence_test.rb

This branch adds methods to find and execute a single test within a sequence. It also adds sample unit tests for a sequence.
The sample sequence was updated to use constants for the test names to avoid duplicating these, but this is a change we may want to revert.
**Submitter:**
Name:
Name:

FI-330: Make sequences more testable

---

lib/app/views/guided.erb
lib/app/views/report.erb

When building the ID attribute of some HTML elements, we would occasionally get double-quotes in the ID string, because we were just dumping an array of Ruby String objects into the ID attribute field. This PR avoids that by calling `.join(',')` on the array, like is already done for the `name` attribute in the same elements.
**Submitter:**
Name:
Name:

FI-423 ID errors

---

lib/app/modules/onc_program/onc_smart_discovery_sequence.rb

This branch removes the SMART capabilities test.
**Submitter:**
- N/A Tests are included and test edge cases
Name:
Name:

FI-431: Remove SMART capabilities test

---

.travis.yml

Adding `cache: bundler` makes Travis cache installed gems between builds. It automatically invalidates the cache and re-runs Bundler when the `Gemfile.lock` changes. Adding this will speed up test runs on Travis.
**Submitter:**
Name:
Name:

Add Bundler caching in Travis to speed up test runs

---

lib/app/models/server_capabilities.rb
lib/app/modules/us_core_guidance/us_core_r4_capability_statement_sequence.rb
test/model/server_capabilities_test.rb
test/sequence/smart/token_refresh_sequence_test.rb
test/sequence/us_core_guidance/us_core_r4_capability_statement_sequence_test.rb

Update the US Core Capability Statement sequence to include a test that checks for support of the US Core Patient profile + one other US Core profile.
**Submitter:**
Name:
Name:

FI-385: Check for US Core profile support

---

lib/app/utils/assertions.rb
test/support/sequence_coverage_reporting.rb

This PR updates the assertion tracking to track assertion calls in helper methods. For assertions not directly called in a test, the output will now look like this:
```
location_of_method_call_in_test -> location_of_assertion
modules/argonaut/argonaut_procedure_sequence.rb:110 => sequence_base.rb:490
```
This allows us to verify that the helper methods are being exercised in each test, rather than only once. The output also differentiates between direct and indirect assertion calls.
A unit test of the following test would record a direct assertion call because the item being unit tested is making the assertion.
```
test 'direct' do
assert true
end
```
A unit test of the following test would record an indirect assertion call because the assertion happens in a separate method. A unit test …

FI-435 Track assertions in helpers

---

generator/uscore/uscore_generator.rb
lib/app/modules/uscore_v3.0.0/us_core_location_sequence.rb
lib/app/modules/uscore_v3.0.0/us_core_organization_sequence.rb
lib/app/modules/uscore_v3.0.1/us_core_location_sequence.rb
lib/app/modules/uscore_v3.0.1/us_core_organization_sequence.rb

Location and Organization sequences had a bug where validating addresses tried to do starts_with, but it should've been start_with?
**Submitter:**
Name:
Name:

Fi 446 fix address checking bug

---

lib/app/sequence_base.rb
lib/app/utils/exceptions.rb
test/unit/sequence_base_test.rb

This branch checks sequences when Inferno starts to ensure test keys are unique within a sequence. A sample failure:
```
ᐅ be rake
INFO | Inferno | Environment: development
rake aborted!
Inferno::InvalidKeyException: Duplicate test key :invalid_refresh_token in TokenRefreshSequence
inferno/lib/app/sequence_base.rb:370:in `test'
inferno/lib/app/modules/smart/token_refresh_sequence.rb:50:in `<class:TokenRefreshSequence>'
...
```
**Submitter:**
Name: @okeefm 
Name:

FI-428: Check for duplicate keys

---

test/unit/sequence_base_test.rb

PR #339 introduced a unit test which created a sequence with test ids starting at 0. The sequence validation test that checks for sequential test ids doesn't like tests starting at 0, so it would fail if it ran after the other test.
**Submitter:**
Name:
Name:

FI-470: Fix order-dependent unit test

---

lib/app/models/resource_reference.rb
lib/app/models/testing_instance.rb
test/sequence/medication_order_sequence_test.rb
test/sequence/r4_provenance_sequence_test.rb
test/sequence/us_core_r4/clinicalnotes_sequence_test.rb
test/unit/test_instance_test.rb

This PR adds a `created_at` timestamp to `ResourceReference` and makes `TestingInstance#patient_id` retrieve the id of the Patient reference which was created first. Previously, the first Patient reference was chosen from a list sorted by a randomly generated id, so the id returned was non-deterministic when multiple Patient references were present.
**Submitter:**
Name:
Name:

FI-473: Make TestingInstance#patient_id deterministic

---

generator/uscore/uscore_generator.rb
lib/modules/uscore_v3.1.0/us_core_allergyintolerance_sequence.rb
lib/modules/uscore_v3.1.0/us_core_careplan_sequence.rb
lib/modules/uscore_v3.1.0/us_core_diagnosticreport_lab_sequence.rb
lib/modules/uscore_v3.1.0/us_core_diagnosticreport_note_sequence.rb
lib/modules/uscore_v3.1.0/us_core_documentreference_sequence.rb
lib/modules/uscore_v3.1.0/us_core_medicationrequest_sequence.rb
lib/modules/uscore_v3.1.0/us_core_practitionerrole_sequence.rb

Resource instance variable names in the US Core sequences were updated recently from `@resourcename` to `@resource_name`, but I missed one spot in the generator. This PR makes all of the names consistent.
**Submitter:**
- n/a Tests are included and test edge cases
Name:
Name: @okeefm 

FI-503: Make resource instance variable names consistent

---

generator/uscore/uscore_generator.rb
lib/modules/uscore_v3.1.0/us_core_diagnosticreport_lab_sequence.rb
lib/modules/uscore_v3.1.0/us_core_diagnosticreport_note_sequence.rb
lib/modules/uscore_v3.1.0/us_core_documentreference_sequence.rb

Removing CREATE interaction tests because they're not read-only. 
**Submitter:**
Name:
Name:

FI-445 Removing create tests

---

generator/uscore/metadata_extractor.rb
generator/uscore/uscore_generator.rb
lib/modules/uscore_v3.1.0/pediatric_bmi_for_age_sequence.rb
lib/modules/uscore_v3.1.0/pediatric_weight_for_height_sequence.rb
lib/modules/uscore_v3.1.0/us_core_careplan_sequence.rb
lib/modules/uscore_v3.1.0/us_core_careteam_sequence.rb
lib/modules/uscore_v3.1.0/us_core_diagnosticreport_lab_sequence.rb
lib/modules/uscore_v3.1.0/us_core_diagnosticreport_note_sequence.rb
lib/modules/uscore_v3.1.0/us_core_observation_lab_sequence.rb
lib/modules/uscore_v3.1.0/us_core_pulse_oximetry_sequence.rb
lib/modules/uscore_v3.1.0/us_core_smokingstatus_sequence.rb

This pull request sets the first search for diagnostic report sequences to patient+category. It also fixes a bug in the generator that made it not get all the values from a valueset.
**Submitter:**
Name:
Name:

Fi 489 - Set first search for diagnosticreport

---

lib/modules/smart/smart_discovery_sequence.rb
lib/modules/smart/test/smart_discovery_sequence_test.rb

Some tests in the SMART Discovery Sequence assume that the SMART well-known endpoint returned valid JSON configuration and fail if no configuration was returned.
This PR makes them skip if no well-known configuration was found.
**Submitter:**
Name:
Name:

FI-402: Fix missing well known errors

---

lib/app/endpoint/oauth2_endpoints.rb
lib/app/endpoint/test_set_endpoints.rb
lib/app/helpers/browser_logic.rb

This PR fixes the issue where during the launch sequences, clicking the cancel button would result in a 404.
**Submitter:**
Name:
Name:

FI-300: Fix cancel link during OAuth tests

---

lib/app/views/default.erb
lib/modules/bulk_data/bulk_data_export_sequence.rb
lib/modules/bulk_data/bulk_data_group_export_sequence.rb
lib/modules/bulk_data/bulk_data_patient_export_sequence.rb
lib/modules/bulk_data/test/patient_export_sequence_test.rb

This pull request contains changes for FI-511. Bulk data export sequence can use bulk_access_token if available.
**Submitter:**
https://oncprojectracking.healthit.gov/support/browse/FI-511
Name:
Name:

FI-511 Apply bulk_access_token to Group export

---

lib/app/models/module/test_case.rb
lib/app/models/module/test_group.rb
lib/app/views/report.erb
lib/app/views/test_case.erb
lib/app/views/test_list.erb
lib/modules/onc_program_module.yml

The problem:  In our test procedure view, you can string together multiple sequences executed against different contexts.  However, their TESTIDs remain the same, which is problematic because they are different tests because they have different inputs.
This addresses the issue by adding an optional 'prefix' field on groups in the module.yml files.  If a prefix exists, the UI (and soon the XLS outputter) appends it to the test.
This is starting to get a little more complicated than I'm comfortable with -- you need to know to append the group id in different views.  Also, I didn't add a test to ensure this is used for uniqueness, as it is just an option.  But we may consider adding this.
should …

FI-509 Add optional group prefixes to ensure unique test ids.

---

lib/app/endpoint.rb

Allow specifying alternate config file location with `INFERNO_CONFIG_FILE`.  This allows us to have downstream forks have fewer merge conficts.
```
cp config.yml config_other.yml
INFERNO_CONFIG_FILE=config_other.yml bundle exec rackup
```
**Submitter:**
Name:
Name:

Fi 526 config env

---

generator/uscore/metadata_extractor.rb
generator/uscore/us_core_unit_test_generator.rb
generator/uscore/uscore_generator.rb
lib/app/sequence_base.rb
lib/app/utils/search_validation.rb
lib/modules/uscore_v3.1.0/pediatric_bmi_for_age_sequence.rb
lib/modules/uscore_v3.1.0/pediatric_weight_for_height_sequence.rb
lib/modules/uscore_v3.1.0/test/pediatric_bmi_for_age_test.rb
lib/modules/uscore_v3.1.0/test/pediatric_weight_for_height_test.rb
lib/modules/uscore_v3.1.0/test/us_core_diagnosticreport_lab_test.rb
lib/modules/uscore_v3.1.0/test/us_core_diagnosticreport_note_test.rb
lib/modules/uscore_v3.1.0/test/us_core_immunization_test.rb
lib/modules/uscore_v3.1.0/test/us_core_observation_lab_test.rb
lib/modules/uscore_v3.1.0/test/us_core_procedure_test.rb
lib/modules/uscore_v3.1.0/test/us_core_pulse_oximetry_test.rb
lib/modules/uscore_v3.1.0/test/us_core_smokingstatus_test.rb
lib/modules/uscore_v3.1.0/us_core_careplan_sequence.rb
lib/modules/uscore_v3.1.0/us_core_condition_sequence.rb
lib/modules/uscore_v3.1.0/us_core_diagnosticreport_lab_sequence.rb
lib/modules/uscore_v3.1.0/us_core_diagnosticreport_note_sequence.rb
lib/modules/uscore_v3.1.0/us_core_documentreference_sequence.rb
lib/modules/uscore_v3.1.0/us_core_encounter_sequence.rb
lib/modules/uscore_v3.1.0/us_core_goal_sequence.rb
lib/modules/uscore_v3.1.0/us_core_immunization_sequence.rb
lib/modules/uscore_v3.1.0/us_core_medicationrequest_sequence.rb
lib/modules/uscore_v3.1.0/us_core_observation_lab_sequence.rb
lib/modules/uscore_v3.1.0/us_core_procedure_sequence.rb
lib/modules/uscore_v3.1.0/us_core_pulse_oximetry_sequence.rb
lib/modules/uscore_v3.1.0/us_core_smokingstatus_sequence.rb
test/unit/sequence_base_test.rb

This PR fixes some of the problems in the tests that were caused by metadata errors. It adds the 'ge', comparator and changes Procedure.occurenceDateTime to Procedure.performedDateTime.
**Submitter:**
Name:
Name:

FI-496 fix metadata errors

---

.travis.yml

Bundler 2.1.0 was released, and workaround we used to make sure bundler was available for travis conflicts with the new bundler.  Removed that workaround because it appears that the version of ruby we are using has access to it.
**Submitter:**
Name:
Name:

fi-542 Fix travis.

---

lib/app/sequence_base.rb

This PR fixes a fatal error when performing a comparator search when trying to resolve from a period type. 
**Submitter:**
Name:
Name:

FI 541 - Fix fatal error with comparator search

---

lib/app/endpoint/home.rb
lib/app/endpoint/oauth2_endpoints.rb
lib/app/endpoint/test_set_endpoints.rb
lib/app/sequence_base.rb
lib/app/views/report.erb
lib/app/views/test_case.erb
lib/app/views/test_list.erb
lib/tasks/tasks.rake
test/unit/sequence_base_test.rb

This PR allows modules to set `hide_optional: true` and not display or run any optional tests. This option already existed, but was not actually implemented.
**Submitter:**
Name:
Name:

FI-538: Allow omission of optional tests

---

generator/uscore/metadata_extractor.rb
generator/uscore/uscore_generator.rb
lib/app/models/server_capabilities.rb
lib/app/models/testing_instance.rb
lib/app/utils/skip_helpers.rb
lib/modules/uscore_v3.1.0/us_core_documentreference_sequence.rb
test/unit/server_capabilities_test.rb

This PR adds a test for the docref operation. It also adds the ability to check the server capabilities for resource operation support. The test itself skips if docref is not supported in the capability statement. It performs the GET request and asserts it's 200 response. I don't check if anything is returned because returning an empty bundle is valid when the server can't generate the CCD. 
**Submitter:**
- [x ] Internal ticket is properly labeled (Community/Program)
Name:
Name:

Fi 481 create docref test

---

lib/app/ext/fhir_client.rb
lib/app/models/testing_instance.rb
lib/modules/smart/shared_launch_tests.rb
lib/modules/smart/test/shared_launch_tests_test.rb
lib/modules/smart/test/token_refresh_sequence_test.rb
test/unit/fhir_client_test.rb

Inferno's tests can take some time, so Inferno needs to be able to automatically refresh access tokens before they expire.
**Submitter:**
Name:
Name:

FI-507: Automatic token refresh

---

lib/modules/smart/token_refresh_sequence.rb

Fixes bug that causes inferno to crash depending on the order that a given environment loads ruby files.
**Submitter:**
Name:
Name:

FI-573 Add reference to a dependent ruby file in token refresh sequence.

---

generator/uscore/metadata_extractor.rb
generator/uscore/templates/unit_tests/chained_search_unit_test.rb.erb
generator/uscore/us_core_unit_test_generator.rb
generator/uscore/uscore_generator.rb
lib/modules/uscore_v3.1.0/test/us_core_practitionerrole_test.rb
lib/modules/uscore_v3.1.0/us_core_practitionerrole_sequence.rb

This branch adds a test for the chained search parameters US Core requires for PractitionerRole (practitioner.name and practitioner.identifier). Although this test was added to the US Core generator, the test itself and its unit test are hard coded. Implementing chained search tests in a generic manner would require a much larger amount of effort and isn't necessary to support these two chained parameters.
**Submitter:**
Name:
Name:

FI-569: Add chained search tests

---

lib/app/ext/fhir_client.rb
test/unit/module_validation_test.rb

This gives the test writer a bit more flexibility by allowing the client to be generated from a different property than `url`.  It also loosens up the requirement for duplicate test names to allow for multiple children of the same parent to be in one module.
**Submitter:**
Name:
Name:

FI-505 Minor updates to allow for multiple urls.

---

test/test_helper.rb

Fixes issue where test helper wraps resources in potentially wrong FHIR version bundle.
**Submitter:**
Name:
Name:

Fi 600 fix build due to test helper issue

---

lib/app/utils/terminology.rb
lib/app/utils/valueset.rb
lib/tasks/tasks.rake

- Updates the version of UMLS from `2018AB` to `2019AB`.
- Create msgpack files with `wb` open mode to avoid encoding issues encountered during debugging.
- Remove ValueSets that use NDF-RT which has been replaced by MED-RT
- [See the 2019AB Release Notes](https://www.nlm.nih.gov/research/umls/knowledge_sources/metathesaurus/release/notes.html)
- Fix issue where `#import_valueset` returned a `Inferno::Terminology::Valueset` instead of the expected `Set`
**Submitter:**
Name:
Name:

Update UMLS Version

---

generator/uscore/uscore_generator.rb
lib/modules/uscore_v3.1.0/us_core_careteam_sequence.rb
lib/modules/uscore_v3.1.0/us_core_medicationrequest_sequence.rb

This makes the composite or searches check if all values being or'd by are found
**Submitter:**
Name:
Name:

check for existence of all composite or values

---

lib/app/ext/fhir_client.rb
lib/modules/smart/test/token_refresh_sequence_test.rb
lib/modules/smart/token_refresh_sequence.rb
lib/modules/uscore_v3.1.0_module.yml
test/unit/fhir_client_test.rb

This branch omits the invalid client ID token refresh test for public clients because that test is only valid for confidential clients. [There is no client ID based authentication for public client during a token refresh.](http://hl7.org/fhir/smart-app-launch/#step-5-later-app-uses-a-refresh-token-to-obtain-a-new-access-token)
**Submitter:**
Name:
Name:

FI-563: Omit invalid client ID token refresh test for public clients

---

lib/app/endpoint/home.rb
lib/app/models/request_response.rb

The `CGI.escapeHTML` method doesn't work if the html is escaped unicode. This branch unescapes all escaped unicode in responses so that html is not rendered when displaying responses.
Before:
After:
**Submitter:**
- n/a Tests are included and test edge cases
Name:
Name:

FI-508: Prevent html rendering in responses

---

lib/app/sequence_base.rb
lib/app/views/test_inputs.erb
lib/app/views/test_list.erb
lib/app/views/test_log.erb
lib/app/views/test_outputs.erb
lib/app/views/test_result_details.erb
public/css/styles.css

This branch allows markdown formatting of error messages, mainly so that we can have multiline error messages. You will probably need to run this in a private window to load the new css.
**Submitter:**
- n/a Tests are included and test edge cases
Name:
Name:

FI-482: Allow error message formatting

---

README.md

Trivial documentation change omitted in 5f4dc088dc0c31d0ee7f89594c8e33e1078c7dda
Already updated in program edition: https://github.com/onc-healthit/inferno-program/commit/eac144a1964c6bbe3c8d7485787e5cd18cafd6d6#diff-04c6e90faac2675aa89e2176d2eec7d8R173
**Submitter:**
Name:
Name:

Update modules path in README.md

---

Gemfile.lock

Updates the `fhir_models` dependency from `4.0.2` to `4.1.0` to get updated R4 Definitions.
Related to: https://github.com/onc-healthit/inferno/issues/449
**Submitter:**
Name:
Name:

Update fhir_models dependency

---

generator/generic/generic_generator.rb
generator/generic/templates/module.yml.erb
lib/app.rb
lib/app/models/module.rb
lib/app/utils/startup_tasks.rb
test/test_helper.rb

This branch integrates the generic generator with the validator service. When Inferno starts up, the resources for any module created via the generic will be posted to the validator service so that it can validate resources. This only works for the contents of an IG package containing the corresponding `package.json`. If no `package.json` is present, the resources are not uploaded to the validator.
This functionality depends on https://github.com/inferno-community/fhir-validator-wrapper/pull/16 and https://github.com/inferno-community/fhir-validator-wrapper/pull/18
Loading inferno's modules has been moved from `Inferno::Module` to a new `Inferno::StartupTasks`. Loading modules now may involve making a POST to an external service, so this change makes it so that you won't make external …

FI-928: Integrate generation with validator

---

config.yml
docker-compose.yml
lib/app/utils/resource_validator_factory.rb
test/test_helper.rb

Defaults the `config.yml` to the external validator and ports the updates from `inferno-program` which enable to unit tests to continue to use the internal validator.  See https://github.com/onc-healthit/inferno-program/pull/22
This PR also updates the `docker-compose.yml` to use `infernocommunity/fhir-validator-service`, which includes the features required by https://github.com/onc-healthit/inferno/pull/476, instead of `infernocommunity/fhir-validator-wrapper`.
`Inferno::App::Endpoint.settings.resource_validator = 'internal'` is also set in `test_helper` because `StartupTasks` directly accesses it in `#external_validator?`.  I debated adding a similar ENV check there, but figured it would be better to contain the logic in the test specific `test_helper` file.

FI-955 Default to External

---

lib/app.rb
lib/app/utils/config_manager.rb
lib/tasks/tasks.rake
test/fixtures/test_config.yml
test/unit/config_manager_test.rb

This PR updates the `generate` rake task to automatically append the generated module to the configuration.  An optional argument allows the user to prevent this from happening.
A `ConfigManager` class was added to help manage loading, updating and writing the config.  I'm not sure if we'll want to use this in more places in the future (instead of `App::Endpoint::settings` and I figure that may be best left for a future PR as the real goal here is to update the `generate` task.
_Note: Adding the newly generated module to the config will remove and comments in an overwritten yaml file_

FI-956: Add Generated Sequence to config.yml

---

generator/generic/search_test.rb
generator/search_parameter_metadata.rb

This PR addresses some bugs in the generic generator involving search parameters. One issue is that the search validation code used to have fhir path expressions that we couldn't handle. For example, the us core laboratory result sequence had the ".where" in the search validation code. This removes the ".where" part. The second is that the patient id parameter was being set to `id` instead of `_id`.  
To test, run the generic generator on the us core resources. Check that the patient sequence's id search is _id instead id and that the ".where" is not included in the lab result sequence.

FI-964 fix bugs with _id search parameter and .where in search validation

---

lib/app/utils/index_builder.rb
lib/app/utils/startup_tasks.rb
test/fixtures/sample_ig/StructureDefinition-Patient.json
test/fixtures/sample_ig/package.json
test/unit/index_builder_test.rb

[FI-957](https://oncprojectracking.healthit.gov/support/browse/FI-957): This PR adds an `IndexBuilder` utility class to handle indexing IG packages (creating an `.index.json` at the root and for all subdirectories). It also `POST`s profiles one-by-one to the validator if no `package.json` is present.
**Submitter:**
Name:
Name:

FI-957: Build .index.json for package tarball or upload standalone profiles

---

lib/tasks/tasks.rake

Addresses #485. Module loading was moved out of `app.rb`, so it needs to be called from the rake tasks that depend on the modules being present.

FI-999: Fix rake tasks

---

config.yml

Update presets to inferno.healthit.gov to be the right patient ids based on the most recent data set.

Update test patients on reference server

---

lib/modules/ips/ips_compositionuvips_sequence.rb
lib/modules/ips/test/fixtures/composition.json
lib/modules/ips/test/fixtures/document_response.json
lib/modules/ips/test/ips_composition_sequence_test.rb

This adds a test for the $document operation on composition. It performs it on the given composition resource and checks if all the referenced resources in it are contained in the bundle returned. I'm not sure how to handle absolute references right now, but I made this PR to have something to test for the connectathon

add document operation test

---

lib/app/ext/fhir_models.rb
lib/app/utils/validation.rb

A recent PR added a monkey patch to `fhir_models` which caused an exception when trying to load resources into a package. For example if a `package.json` is in the resources directory for an IG then it will fail. This breaks loading resources for an IG like IPS

Fix IG Resource Validator Loading

---

lib/version.rb

Missed updating the version file in v2.12.0.  Since this is community, and it is only really 'informational' for the user, I don't think it is a huge deal that our release doesn't reflect it, but if there is an easy way to fix the tags we can give it a shot (probably not).  We could alternatively do a quick v2.12.1 release that updates it again?

Update version file.

---

config.yml

We recently upgraded our reference server to allow users to preconfigure a static bearer token that always work.  Update the config to prefill that for the reference server for ease of use purposes.  Note that this will technically not work until the new reference server is deployed, but since it isn't prefilled now anyhow, this doesn't really hurt things.
See https://github.com/onc-healthit/inferno.healthit.gov/pull/71
Bearer token for single patient api tests will be prefilled for localhost us core v3.1.1 tests against https://inferno.healthit.gov/reference-server.   Note that it won't work on the currently deployed

Prefill bearer token on reference server for ease of use.

---

lib/modules/us_core_guidance/us_core_r4_capability_statement_sequence.rb

C-02 should now run warnings when the following profiles are not supported (in addition to what was previously there). I.E this should match program. Essentially C-02 should match USCCAP-02 in inferno program.
'http://hl7.org/fhir/StructureDefinition/bp',
'http://hl7.org/fhir/StructureDefinition/bodyheight',
'http://hl7.org/fhir/StructureDefinition/bodyweight',
'http://hl7.org/fhir/StructureDefinition/heartrate',
'http://hl7.org/fhir/StructureDefinition/resprate',
'http://hl7.org/fhir/StructureDefinition/bodytemp',
'http://hl7.org/fhir/us/core/StructureDefinition/head-occipital-frontal-circumference-percentile'
should check the relevant check boxes when the associated item is done. For items …

Updated supported profiles to match program's capability test

---

lib/modules/smart_scheduling_links/smart_scheduling_links_basic_sequence.rb
lib/modules/smart_scheduling_links_module.yml

The current version of Inferno currently requires users to paste in a 'true' FHIR URL, but the way the IG is written makes it seem like the logical starting point should be {fhir_url}/$bulk-publish.  This just auto-removes $bulk-publish from the FHIR URL in the first test if someone pasts that in to avoid that confusion..
Also, some minor wording updates.
If you paste in a url ending in $bulk-publish the tests should run properly.
Very minor update to first test.
Tests to both of the following URLs should now properly download the manifest:
* https://raw.githubusercontent.com/smart-on-fhir/smart-scheduling-links/master/examples
* https://raw.githubusercontent.com/smart-on-fhir/smart-scheduling-links/master/examples/$bulk-publish

Update so that fhir url can include $bulk-publish

---

lib/modules/smart_scheduling_links/smart_scheduling_links_basic_sequence.rb
lib/modules/smart_scheduling_links_module.yml

Some servers (particularly sandbox servers) require a custom header.  This IG does allow for custom security measures, which often are represented as custom headers.  However, it is discouraed, so we flag it as a warning.
You can now add a custom header and it will be sent in all requests.
Added input box and code to send them as a header.  Also included a minor fix on the vtrx test.
Fill out customer header field and you will see the custom header being sent.

Allow custom header and fix vtrx identifier test.

---

lib/modules/smart_scheduling_links/smart_scheduling_links_basic_sequence.rb
resources/smart_scheduling_links/ImplementationGuide-smart.scheduling.links.json
resources/smart_scheduling_links/StructureDefinition-c19-service-codeable-concept.json
resources/smart_scheduling_links/StructureDefinition-vaccine-product.json
resources/smart_scheduling_links/StructureDefinition-vaccine-schedule.json

* Removes some buggy extension validation code in the `Schedule` test for SMART Scheduling Links. No longer needed, as the presence and format of the extensions is now tested through rules on `Schedule` in the profiles supplied to the validator.
* Update the profiles supplied to the validator.
* No longer test for presence of `vaccine-product` and `vaccine-dose` extensions on `Schedule` through the module code
* Add rules with a warning binding strength to the `Schedule` StructureDefinition checking for the presence of at least 1 of each extension
* Add Josh's slices on serviceType, as listed here: https://github.com/inferno-community/fsh-smart-scheduling-links/pull/6
* Remove code testing for presence of `vaccine-product` and `vaccine-dose` extensions
* Update …

Remove Schedule extension-validation code in favor of validating it through the HL7 validator, and update one of the StructureDefinitions

---

lib/app/utils/hl7_validator.rb
lib/modules/uscore_v3.1.1/us_core_location_sequence.rb
test/unit/hl7_validator_test.rb

This PR switches off terminology validation in Inferno-community, and re-enables displaying warnings from the validator wrapper regarding invalid codes
* Remove a call to validate a code in one of the US Core sequences
* Stop treating `code-invalid` errors as informational messages

FI-1206 use tx.fhir.org

---

lib/app/utils/startup_tasks.rb

This PR makes it so that `lib/app/utils/startup_tasks.rb` will upload resources from included IGs that match any of the Conformance resource types from https://www.hl7.org/fhir/conformance-module.html
Previously, it would only load `StructureDefinition` resources, which left out a number of the desired artifacts
* Added a `CONFORMANCE_RESOURCE_TYPES` array constant to `Inferno::StartupTasks`
* Load a resource if its type matches any in the above constant
Run Inferno with a local validator wrapper, and check that the number of `POST /profile` calls in the logs matches the number of resources for each IG that should be uploaded.

Switch from only POSTing StructureDefinitions to the validator service, to POSTing all conformance-related resource types

---

lib/modules/smart_scheduling_links/smart_scheduling_links_basic_sequence.rb
lib/modules/smart_scheduling_links/test/smart_scheduling_basic_test.rb

Validate that the transactionTime in the scheduling links manifest is a valid date and that it has a timezone offset as required in the spec.
See https://chat.fhir.org/#narrow/stream/281612-smart.2Fscheduling-links/topic/Publisher.3A.20Rite-Aid/near/243572426
Will fail if the transactionTime is not a valid time and is missing the timezone.
Updated one of the scheduling links tests and the tests of them.
It is difficult to mock up a failure case (hopefully the unit tests are good enough for that), but validate against valid cases to ensure it doesn't introduce incorrect failures.

Validate transactionTime in scheduling links manifest.

---

db/config.postgres.yml
db/config.yml
db/migrate/20210804135524_add_request_index.rb
db/schema.rb
lib/app/utils/startup_tasks.rb

This branch adds the missing index to join table to fix performance issues as the table size increases.
Also allows erb to be used in the database configuration so that values can be loaded from environment variables.
This should work:
```
docker-compose -f docker-compose.postgres.yml build
docker-compose -f docker-compose.postgres.yml up
```
You can validate that the environment variables work by adding something like this to the inferno service in `docker-compose.postgres.yml`, which will cause inferno to fail to connect to the database.
```
environment:
INFERNO_DB_USERNAME: xyz
```

FI-1292/1293 Add missing index and allow dynamic content in db config

---

lib/app/models/request_response.rb
test/unit/request_response_test.rb

Prevents receiving an invalid header from crashing Inferno. If you get rid of the rescue in `RequestResponse.stringify_headers`, an exception will cause the unit test to fail. Also copied over the other unit test that existed in program but not community.

FI-1302: Catch error from invalid headers
